using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public static class Constants
{
    public static string serverUrl = "http://wowrandom.ru";

    public static Dictionary<string, string> countries = new Dictionary<string, string>{
        {"AB", "Abkhazia"},
        {"AU", "Australia"},
        {"AT", "Austria"},
        {"AZ", "Azerbaijan"},
        {"AL", "Albania"},
        {"DZ", "Algeria"},
        {"AS", "American Samoa"},
        {"AI", "Anguilla"},
        {"AO", "Angola"},
        {"AD", "Andorra"},
        {"AQ", "Antarctica"},
        {"AG", "Antigua and Barbuda"},
        {"AR", "Argentina"},
        {"AM", "Armenia"},
        {"AW", "Aruba"},
        {"AF", "Afghanistan"},
        {"BS", "Bahamas"},
        {"BD", "Bangladesh"},
        {"BB", "Barbados"},
        {"BH", "Bahrain"},
        {"BY", "Belarus"},
        {"BZ", "Belize"},
        {"BE", "Belgium"},
        {"BJ", "Benin"},
        {"BM", "Bermuda"},
        {"BG", "Bulgaria"},
        {"BO", "Bolivia, plurinational state of"},
        {"BQ", "Bonaire, Sint Eustatius and Saba"},
        {"BA", "Bosnia and Herzegovina"},
        {"BW", "Botswana"},
        {"BR", "Brazil"},
        {"IO", "British Indian Ocean Territory"},
        {"BN", "Brunei Darussalam"},
        {"BF", "Burkina Faso"},
        {"BI", "Burundi"},
        {"BT", "Bhutan"},
        {"VU", "Vanuatu"},
        {"HU", "Hungary"},
        {"VE", "Venezuela"},
        {"VG", "Virgin Islands, British"},
        {"VI", "Virgin Islands, U.S."},
        {"VN", "Vietnam"},
        {"GA", "Gabon"},
        {"HT", "Haiti"},
        {"GY", "Guyana"},
        {"GM", "Gambia"},
        {"GH", "Ghana"},
        {"GP", "Guadeloupe"},
        {"GT", "Guatemala"},
        {"GN", "Guinea"},
        {"GW", "Guinea-Bissau"},
        {"DE", "Germany"},
        {"GG", "Guernsey"},
        {"GI", "Gibraltar"},
        {"HN", "Honduras"},
        {"HK", "Hong Kong"},
        {"GD", "Grenada"},
        {"GL", "Greenland"},
        {"GR", "Greece"},
        {"GE", "Georgia"},
        {"GU", "Guam"},
        {"DK", "Denmark"},
        {"JE", "Jersey"},
        {"DJ", "Djibouti"},
        {"DM", "Dominica"},
        {"DO", "Dominican Republic"},
        {"EG", "Egypt"},
        {"ZM", "Zambia"},
        {"EH", "Western Sahara"},
        {"ZW", "Zimbabwe"},
        {"IL", "Israel"},
        {"IN", "India"},
        {"ID", "Indonesia"},
        {"JO", "Jordan"},
        {"IQ", "Iraq"},
        {"IR", "Iran, Islamic Republic of"},
        {"IE", "Ireland"},
        {"IS", "Iceland"},
        {"ES", "Spain"},
        {"IT", "Italy"},
        {"YE", "Yemen"},
        {"CV", "Cape Verde"},
        {"KZ", "Kazakhstan"},
        {"KH", "Cambodia"},
        {"CM", "Cameroon"},
        {"CA", "Canada"},
        {"QA", "Qatar"},
        {"KE", "Kenya"},
        {"CY", "Cyprus"},
        {"KG", "Kyrgyzstan"},
        {"KI", "Kiribati"},
        {"CN", "China"},
        {"CC", "Cocos (Keeling) Islands"},
        {"CO", "Colombia"},
        {"KM", "Comoros"},
        {"CG", "Congo"},
        {"CD", "Congo, Democratic Republic of the"},
        {"KP", "Korea, Democratic People's republic of"},
        {"KR", "Korea, Republic of"},
        {"CR", "Costa Rica"},
        {"CI", "Cote d'Ivoire"},
        {"CU", "Cuba"},
        {"KW", "Kuwait"},
        {"CW", "CuraГ§ao"},
        {"LA", "Lao People's Democratic Republic"},
        {"LV", "Latvia"},
        {"LS", "Lesotho"},
        {"LB", "Lebanon"},
        {"LY", "Libyan Arab Jamahiriya"},
        {"LR", "Liberia"},
        {"LI", "Liechtenstein"},
        {"LT", "Lithuania"},
        {"LU", "Luxembourg"},
        {"MU", "Mauritius"},
        {"MR", "Mauritania"},
        {"MG", "Madagascar"},
        {"YT", "Mayotte"},
        {"MO", "Macao"},
        {"MW", "Malawi"},
        {"MY", "Malaysia"},
        {"ML", "Mali"},
        {"UM", "United States Minor Outlying Islands"},
        {"MV", "Maldives"},
        {"MT", "Malta"},
        {"MA", "Morocco"},
        {"MQ", "Martinique"},
        {"MH", "Marshall Islands"},
        {"MX", "Mexico"},
        {"FM", "Micronesia, Federated States of"},
        {"MZ", "Mozambique"},
        {"MD", "Moldova"},
        {"MC", "Monaco"},
        {"MN", "Mongolia"},
        {"MS", "Montserrat"},
        {"MM", "Burma"},
        {"NA", "Namibia"},
        {"NR", "Nauru"},
        {"NP", "Nepal"},
        {"NE", "Niger"},
        {"NG", "Nigeria"},
        {"NL", "Netherlands"},
        {"NI", "Nicaragua"},
        {"NU", "Niue"},
        {"NZ", "New Zealand"},
        {"NC", "New Caledonia"},
        {"NO", "Norway"},
        {"AE", "United Arab Emirates"},
        {"OM", "Oman"},
        {"BV", "BV"},
        {"IM", "IM"},
        {"NF", "NF"},
        {"CX", "CX"},
        {"HM", "HM"},
        {"KY", "KY"},
        {"CK", "CK"},
        {"TC", "TC"},
        {"PK", "Pakistan"},
        {"PW", "Palau"},
        {"PS", "PA"},
        {"PA", "Panama"},
        {"VA", "VA"},
        {"PG", "PG"},
        {"PY", "Paraguay"},
        {"PE", "Peru"},
        {"PN", "Pitcairn"},
        {"PL", "Poland"},
        {"PT", "Portugal"},
        {"PR", "PR"},
        {"MK", "MK"},
        {"RE", "Reunion"},
        {"RU", "Russia"},
        {"RW", "Rwanda"},
        {"RO", "Romania"},
        {"WS", "Samoa"},
        {"SM", "SM"},
        {"ST", "ST"},
        {"SA", "SA"},
        {"SH", "SH"},
        {"MP", "MP"},
        {"BL", "BL"},
        {"MF", "MF"},
        {"SN", "Senegal"},
        {"VC", "VC"},
        {"KN", "KN"},
        {"LC", "LC"},
        {"PM", "PM"},
        {"RS", "Serbia"},
        {"SC", "Seychelles"},
        {"SG", "Singapore"},
        {"SX", "SX"},
        {"SY", "SY"},
        {"SK", "Slovakia"},
        {"SI", "Slovenia"},
        {"GB", "GB"},
        {"US", "US"},
        {"SB", "SB"},
        {"SO", "Somalia"},
        {"SD", "Sudan"},
        {"SR", "Suriname"},
        {"SL", "SL"},
        {"TJ", "TJ"},
        {"TH", "Thailand"},
        {"TW", "TW"},
        {"TZ", "TZ"},
        {"TL", "TL"},
        {"TG", "Togo"},
        {"TK", "Tokelau"},
        {"TO", "Tonga"},
        {"TT", "TT"},
        {"TV", "Tuvalu"},
        {"TN", "Tunisia"},
        {"TM", "TM"},
        {"TR", "Turkey"},
        {"UG", "Uganda"},
        {"UZ", "Uzbekistan"},
        {"UA", "Ukraine"},
        {"WF", "WF"},
        {"UY", "Uruguay"},
        {"FO", "FO"},
        {"FJ", "Fiji"},
        {"PH", "PH"},
        {"FI", "Finland"},
        {"FK", "FK"},
        {"FR", "France"},
        {"GF", "GF"},
        {"PF", "PF"},
        {"TF", "TF"},
        {"HR", "Croatia"},
        {"CF", "CF"},
        {"TD", "Chad"},
        {"ME", "ME"},
        {"CZ", "CZ"},
        {"CL", "Chile"},
        {"CH", "CH"},
        {"SE", "Sweden"},
        {"SJ", "SJ"},
        {"LK", "LK"},
        {"EC", "Ecuador"},
        {"GQ", "GQ"},
        {"AX", "AX"},
        {"SV", "SV"},
        {"ER", "Eritrea"},
        {"SZ", "Eswatini"},
        {"EE", "Estonia"},
        {"ET", "Ethiopia"},
        {"ZA", "ZA"},
        {"GS", "GS"},
        {"OS", "OS"},
        {"SS", "SS"},
        {"JM", "Jamaica"},
        {"JP", "Japan"},
        {"OO", "-"}
    };
}
